### ISSUE TITLE
Version 3.6.3 failed to start on arm64 machine.

### ISSUE THREAD

**Issue by IAseven** [31z4/zookeeper-docker#140]
### Expected behavior

running 

### Actual behavior
```
aiops-zk           | /opt/java/openjdk/bin/java
aiops-zk           | ZooKeeper JMX enabled by default
aiops-zk           | Using config: /conf/zoo.cfg
aiops-zk           | Error: Could not find or load main class org.apache.zookeeper.server.quorum.QuorumPeerMain
aiops-zk           | Caused by: java.lang.ClassNotFoundException: org.apache.zookeeper.server.quorum.QuorumPeerMain
```

![图片](https://user-images.githubusercontent.com/38178039/183885247-4678da98-7ca2-41b8-aba5-5184a672ed85.png)

### Steps to reproduce the behavior

```
# 服务
services:
  aiops-zk:
    image: zookeeper:3.6.3
    container_name: aiops-zk
    # restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data/zookeeper/data:/data
    networks:
      - network
```

### System configuration
```
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           2
NUMA node(s):        2
Vendor ID:           ARM
Model:               1
Model name:          Neoverse-N1
Stepping:            r3p1
BogoMIPS:            50.00
L1d cache:           64K
L1i cache:           64K
L2 cache:            512K
L3 cache:            32768K
NUMA node0 CPU(s):   0
NUMA node1 CPU(s):   1
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
```
