### ISSUE TITLE
Without `clientPort` config ZooKeeper won't actually listen to the port

### ISSUE THREAD

**Issue by tungd** [31z4/zookeeper-docker#49]
***Before you file an issue here, please keep in mind that your issue may be not related to the image itself. Please make sure that it is, otherwise report the issue [upstream](https://issues.apache.org/jira/projects/ZOOKEEPER/issues).***

### Expected behavior

Simple config like this should just work:

```yaml
version: '3'
services:
  zookeeper:
    image: zookeeper:3.5
    ports:
      - 2181:2181
    environment:
      - ZOO_SERVERS=server.1=0.0.0.0:2888:3888
```

### Actual behavior

However it isn't, the server did start but it wasn't listening to port 2181. The fix is to modify the `entrypoint.sh` to include this config by default.
