### ISSUE TITLE
Strange port issue when using 3.5 with docker-compose

### ISSUE THREAD

**Issue by aiqingyuyan** [31z4/zookeeper-docker#65]
Not sure if it's just my problem or not. I am using the provided `docker-compose.yml` example in the documentation. When I started on local, all 3 containers started up, but when I went into containers themselves and ran `./zkServer.sh status`, all of them gave me the following output:

```
ZooKeeper JMX enabled by default
Using config: /conf/zoo.cfg
Client port not found in static config file. Looking in dynamic config file.
grep: : No such file or directory
Client port not found. Terminating.
```

zookeeper cannot start

But then when I switch zookeeper version to 3.4, everything works perfectly, zookeeper starts correctly, I can connect to each of the node using `zkCli.sh`

### Expected behavior

Using the provided `docker-compose.yml` example with zookeeper:3.5 on local, zookeeper should start correctly, no port issue

### Actual behavior

Cannot find port

### Steps to reproduce the behavior

1. Using the following compose file
```yaml
version: '3.1'

services:
  zoo1:
    image: zookeeper:3.5
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo2:
    image: zookeeper:3.5
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888

  zoo3:
    image: zookeeper:3.5
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
```

and run `docker-compose up -d`

2. Go into any of the containers, then cd to `bin` folder, and ran `./zkServer.sh status`

### System configuration

MacBook Pro
Intel Core i7
Memory:	16 GB
