### ISSUE TITLE
logs will be missing when mounting logs and conf at the same time

### ISSUE THREAD

**Issue by icql** [31z4/zookeeper-docker#69]
logs will be missing when mounting logs and conf at the same time.
zookeeper 3.5.5

### Expected behavior

the log4j file should exist.

### Actual behavior

the log4j file is missing.

### Steps to reproduce the behavior

docker-compose up by the following configuration file.

### System configuration

docker-compose.yml

``` 
version: '3.1'

services:
  zoo1:
    image: zookeeper:3.5.5
    restart: always
    hostname: zoo1
    container_name: zookeeper_1
    ports:
      - 2181:2181
    volumes:
      - /app/zookeeper/zoo1/data:/data
      - /app/zookeeper/zoo1/datalog:/datalog
      - /app/zookeeper/zoo1/logs:/logs
      - /app/zookeeper/zoo1/conf:/conf
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_LOG4J_PROP: "INFO,ROLLINGFILE"
      ZOO_ADMINSERVER_ENABLED: "false"

  zoo2:
    image: zookeeper:3.5.5
    restart: always
    hostname: zoo2
    container_name: zookeeper_2
    ports:
      - 2182:2181
    volumes:
      - /app/zookeeper/zoo2/data:/data
      - /app/zookeeper/zoo2/datalog:/datalog
      - /app/zookeeper/zoo2/logs:/logs
      - /app/zookeeper/zoo2/conf:/conf
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_LOG4J_PROP: "INFO,ROLLINGFILE"
      ZOO_ADMINSERVER_ENABLED: "false"

  zoo3:
    image: zookeeper:3.5.5
    restart: always
    hostname: zoo3
    container_name: zookeeper_3
    ports:
      - 2183:2181
    volumes:
      - /app/zookeeper/zoo3/data:/data
      - /app/zookeeper/zoo3/datalog:/datalog
      - /app/zookeeper/zoo3/logs:/logs
      - /app/zookeeper/zoo3/conf:/conf
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_LOG4J_PROP: "INFO,ROLLINGFILE"
      ZOO_ADMINSERVER_ENABLED: "false"
```
