### ISSUE TITLE
Zookeeper has problems at a period of time under swarm mode

### ISSUE THREAD

**Issue by kervin521** [31z4/zookeeper-docker#81]
***Before you file an issue here, please keep in mind that your issue may be not related to the image itself. Please make sure that it is, otherwise report the issue [upstream](https://issues.apache.org/jira/projects/ZOOKEEPER/issues).***

### Exception 
<font color=red>Exception causing close of session 0x0: ZooKeeperServer not running</font>

## swarm service
```yml
version: '3.7'
services:
   zookeeper-101:
      image: zookeeper:3.5.5
      restart: always
      environment:
         ZOO_MY_ID: 101
         ZOO_TICK_TIME: 10000
         ZOO_INIT_LIMIT: 6
         ZOO_SYNC_LIMIT: 6
         ZOO_MAX_CLIENT_CNXNS: 100
         ZOO_STANDALONE_ENABLED: 'false'
         ZOO_ADMINSERVER_ENABLED: 'true'
         ZOO_AUTOPURGE_PURGEINTERVAL: 0
         ZOO_AUTOPURGE_SNAPRETAINCOUNT: 3
         ZOO_4LW_COMMANDS_WHITELIST: srvr
         ZOO_SERVERS: server.101=0.0.0.0:2888:3888;2181 server.112=zookeeper-112:2888:3888;2181 server.108=zookeeper-108:2888:3888;2181 server.118=zookeeper-118:2888:3888;2181
      volumes:
      - /opt/deploy/data/zookeeper/data:/data
      - /opt/deploy/data/zookeeper/datalog:/datalog
      - /opt/deploy/data/zookeeper/logs:/logs
      - /etc/localtime:/etc/localtime
      ports:
      - 2181:2181
      - 28081:8080
      deploy:
         replicas: 1
         placement:
            constraints:
            - node.hostname==dbs-server101
   zookeeper-112:
      image: zookeeper:3.5.5
      restart: always
      environment:
         ZOO_MY_ID: 112
         ZOO_TICK_TIME: 10000
         ZOO_INIT_LIMIT: 6
         ZOO_SYNC_LIMIT: 6
         ZOO_MAX_CLIENT_CNXNS: 100
         ZOO_STANDALONE_ENABLED: 'false'
         ZOO_ADMINSERVER_ENABLED: 'true'
         ZOO_AUTOPURGE_PURGEINTERVAL: 0
         ZOO_AUTOPURGE_SNAPRETAINCOUNT: 3
         ZOO_4LW_COMMANDS_WHITELIST: srvr
         ZOO_SERVERS: server.101=zookeeper-101:2888:3888;2181 server.112=0.0.0.0:2888:3888;2181 server.108=zookeeper-108:2888:3888;2181 server.118=zookeeper-118:2888:3888;2181
      volumes:
      - /opt/deploy/data/zookeeper/data:/data
      - /opt/deploy/data/zookeeper/datalog:/datalog
      - /opt/deploy/data/zookeeper/logs:/logs
      - /etc/localtime:/etc/localtime
      ports:
      - 2182:2181
      - 28082:8080
      deploy:
         replicas: 1
         placement:
            constraints:
            - node.hostname==dbs-server112
   zookeeper-108:
      image: zookeeper:3.5.5
      restart: always
      environment:
         ZOO_MY_ID: 108
         ZOO_TICK_TIME: 10000
         ZOO_INIT_LIMIT: 6
         ZOO_SYNC_LIMIT: 6
         ZOO_MAX_CLIENT_CNXNS: 100
         ZOO_STANDALONE_ENABLED: 'false'
         ZOO_ADMINSERVER_ENABLED: 'true'
         ZOO_AUTOPURGE_PURGEINTERVAL: 0
         ZOO_AUTOPURGE_SNAPRETAINCOUNT: 3
         ZOO_4LW_COMMANDS_WHITELIST: srvr
         ZOO_SERVERS: server.101=zookeeper-101:2888:3888;2181 server.112=zookeeper-112:2888:3888;2181 server.108=0.0.0.0:2888:3888;2181 server.118=zookeeper-118:2888:3888;2181
      volumes:
      - /opt/deploy/data/zookeeper/data:/data
      - /opt/deploy/data/zookeeper/datalog:/datalog
      - /opt/deploy/data/zookeeper/logs:/logs
      - /etc/localtime:/etc/localtime
      ports:
      - 2183:2181
      - 28083:8080
      deploy:
         replicas: 1
         placement:
            constraints:
            - node.hostname==dbs-server108
   zookeeper-118:
      image: zookeeper:3.5.5
      restart: always
      environment:
         ZOO_MY_ID: 118
         ZOO_TICK_TIME: 10000
         ZOO_INIT_LIMIT: 6
         ZOO_SYNC_LIMIT: 6
         ZOO_MAX_CLIENT_CNXNS: 100
         ZOO_STANDALONE_ENABLED: 'false'
         ZOO_ADMINSERVER_ENABLED: 'true'
         ZOO_AUTOPURGE_PURGEINTERVAL: 0
         ZOO_AUTOPURGE_SNAPRETAINCOUNT: 3
         ZOO_4LW_COMMANDS_WHITELIST: srvr
         ZOO_SERVERS: server.101=zookeeper-101:2888:3888;2181 server.112=zookeeper-112:2888:3888;2181 server.108=zookeeper-108:2888:3888;2181 server.118=0.0.0.0:2888:3888;2181
      volumes:
      - /opt/deploy/data/zookeeper/data:/data
      - /opt/deploy/data/zookeeper/datalog:/datalog
      - /opt/deploy/data/zookeeper/logs:/logs
      - /etc/localtime:/etc/localtime
      ports:
      - 2184:2181
      - 28084:8080
      deploy:
         replicas: 1
         placement:
            constraints:
            - node.hostname==dbs-server118
```
